### ISSUE TITLE
Because of `require('fs')`, it can't be packed with webpack.

### ISSUE THREAD

**Issue by heroboy** [SabakiHQ/deadstones#1]

**Comment by yishn** [comment]
Can you explain a little more in detail?

**Comment by yishn** [comment]
You can alias `fs` to a shim, or set as external inside webpack‘s config.

**Comment by heroboy** [comment]
I see I can configure webpack to solve this problem. I open this issue mainly because Sabaki itself use webpack, so I think this should be more friendly to webpack.

**Comment by yishn** [comment]
If you have a proposal, feel free to submit a pull request. But I want this module still be able to work with Node.js out of the box.

**Comment by apetresc** [comment]
Late follow-up, but this is actually resolved as of 2.2.0. The loader is now lazy and fetch-first: `loadWasm` runs on the first call rather than eagerly on import, so a webpack/browser bundle never hits the `require('fs')` path at runtime. Call `useFetch('.../deadstones_bg.wasm')` after import and it loads via fetch. This came in through #9 (thanks @adamreisnz) reworked in #12.
